"""Render operator boards and status reports from durable state."""

from .coordination import reconcile_conn
from .core import ACTIVE_TASK_STATES, utcnow
from .diagnostics import doctor
from .queries import mission_snapshot
from .storage import connect, mission, mission_mode, runtime_state


def brief_status(conn):
    """Summarize current work without loading every task, event, or artifact."""
    current = mission(conn)
    control = runtime_state(conn)
    counts = dict(conn.execute("SELECT status,COUNT(*) FROM tasks GROUP BY status"))
    decisions = conn.execute(
        "SELECT id,question FROM decisions WHERE status='OPEN' ORDER BY created_at LIMIT 6"
    ).fetchall()
    unknown_effects = conn.execute("SELECT COUNT(*) FROM effects WHERE state='UNKNOWN'").fetchone()[
        0
    ]
    unknown_deliveries = conn.execute(
        "SELECT COUNT(*) FROM deliveries WHERE status='UNKNOWN'"
    ).fetchone()[0]
    outcome = control.get("outcome")
    state = current["status"] if control["desired_state"] == "ACTIVE" else control["desired_state"]
    lines = [
        current["objective"][:500],
        "%s · %s%s" % (mission_mode(conn), state, " · " + outcome if outcome else ""),
        "Tasks: "
        + (
            ", ".join("%s %s" % (count, status.lower()) for status, count in sorted(counts.items()))
            or "none yet"
        ),
    ]
    if decisions:
        lines.append("Needs an answer:")
        lines.extend(
            "  %s: %s" % (row["id"], row["question"].replace("\n", " ")[:180])
            for row in decisions[:5]
        )
        if len(decisions) > 5:
            lines.append("  More questions: swarmctl decision list")
    if unknown_effects or unknown_deliveries:
        lines.append(
            "Needs provider reconciliation: %s effects, %s deliveries"
            % (unknown_effects, unknown_deliveries)
        )
    if control["desired_state"] in {"CANCELLED", "ABANDONED"}:
        next_step = "Review the final report with swarmctl report."
    elif control["desired_state"] != "ACTIVE":
        next_step = "Inspect swarmctl why before deciding whether to resume."
    elif decisions:
        next_step = (
            "Read swarmctl decision show %s, then record an answer with decision resolve."
            % decisions[0]["id"]
        )
    elif unknown_effects or unknown_deliveries:
        next_step = "Inspect swarmctl why and verify provider state before retrying."
    elif current["status"] == "DONE":
        next_step = "Read the result with swarmctl report."
    elif counts.get("RUNNING") or counts.get("CLAIMED"):
        next_step = "Workers are active; swarmctl report shows their latest progress."
    elif counts.get("WAITING_EXTERNAL"):
        next_step = (
            "Inspect swarmctl wait list; the controller wakes work when a signal or check is due."
        )
    elif counts.get("READY"):
        next_step = "Run swarmctl run to continue ready work with your configured harness."
    elif not counts and mission_mode(conn) == "SERVICE":
        next_step = (
            "The service is idle. Submit a case through your ingress adapter or swarmctl case open."
        )
    else:
        next_step = "Run swarmctl run for the manager to plan or review work."
    lines.append("Next: " + next_step)
    return "\n".join(lines)


def md_escape(value):
    return str(value or "").replace("|", "\\|").replace("\n", " ")


def completion_label(entity):
    outcome = entity.get("completion_outcome")
    return entity["status"] + (" / " + outcome if outcome else "")


def forecast_text(workstream):
    if workstream.get("status") == "DONE":
        return "Completed %s" % workstream.get("updated_at", "at an unrecorded time")
    if workstream.get("status") == "CANCELLED":
        return "Cancelled"
    earliest = workstream.get("forecast_earliest")
    latest = workstream.get("forecast_latest")
    confidence = workstream.get("forecast_confidence")
    if earliest and latest:
        window = "%s to %s" % (earliest, latest)
    elif latest:
        window = "by %s" % latest
    elif earliest:
        window = "not before %s" % earliest
    else:
        return "Unknown; no evidence-backed forecast recorded"
    return "%s (%s confidence)" % (window, confidence or "unspecified")


def render_board(root):
    conn = connect(root)
    try:
        reconcile_conn(conn)
        snapshot = mission_snapshot(conn)
    finally:
        conn.close()
    m = snapshot["mission"]
    lines = [
        "# Swarm board",
        "",
        "Generated from canonical state. Do not edit this file by hand.",
        "",
        "- Mission: `%s`" % m["id"],
        "- Mode: **%s**" % m["mode"],
        "- Status: **%s**" % m["status"],
        "- Control: **%s**" % snapshot["runtime"]["desired_state"],
        "- Outcome: **%s**" % (snapshot["runtime"]["outcome"] or "Not yet completed"),
        "- Phase: **%s**" % m["phase"],
        "- Updated: %s" % m["updated_at"],
        "",
        "## Objective",
        "",
        m["objective"],
        "",
        "## Success conditions",
        "",
    ]
    lines.extend(["- %s" % item for item in m["success"]] or ["- None recorded"])
    lines.extend(["", "## Constraints", ""])
    lines.extend(["- %s" % item for item in m["constraints"]] or ["- None recorded"])
    open_findings = [item for item in snapshot["findings"] if item["status"] == "OPEN"]
    active_waits = [item for item in snapshot["external_waits"] if item["status"] == "WAITING"]
    deadline_wakes = [item for item in snapshot["external_waits"] if item["requires_attention"]]
    lines.extend(["", "## Needs attention", ""])
    attention = []
    for finding in open_findings:
        if finding["significance"] == "URGENT":
            attention.append(
                "- Urgent finding `%s` from `%s`: %s"
                % (
                    finding["id"],
                    finding["source_task_id"],
                    md_escape(finding["summary"]),
                )
            )
    for wait in deadline_wakes:
        attention.append(
            "- Deadline reached for wait `%s` on task `%s`; verify `%s` now."
            % (
                wait["id"],
                wait["task_id"],
                md_escape(wait["condition"]),
            )
        )
    lines.extend(attention or ["No urgent findings or missed external-wait deadlines."])
    lines.extend(
        [
            "",
            "## External waits",
            "",
            "| Wait | Task | State | Condition | External ref | Age | Next check | Deadline | Wake reason |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
    )
    recent_wakes = sorted(
        [item for item in snapshot["external_waits"] if item["status"] != "WAITING"],
        key=lambda item: item["updated_at"],
        reverse=True,
    )[:20]
    for wait in active_waits + recent_wakes:
        lines.append(
            "| `%s` | `%s` | %s | %s | %s | %ss | %s | %s | %s |"
            % (
                wait["id"],
                wait["task_id"],
                wait["status"],
                md_escape(wait["condition"]),
                md_escape(wait["external_ref"]),
                wait["waiting_seconds"],
                wait["next_check_at"] or "signal only",
                wait["deadline_at"],
                wait["wake_reason"] or "—",
            )
        )
    if not active_waits and not recent_wakes:
        lines.append("| — | — | — | No external waits | — | — | — | — | — |")
    lines.extend(
        [
            "",
            "## Findings",
            "",
            "| Finding | Significance | State | Source task | Summary | Evidence | Age | Recommendation | Disposition |",
            "|---|---|---|---|---|---|---|---|---|",
        ]
    )
    recent_findings = sorted(
        [item for item in snapshot["findings"] if item["status"] != "OPEN"],
        key=lambda item: item["updated_at"],
        reverse=True,
    )[:20]
    for finding in open_findings + recent_findings:
        lines.append(
            "| `%s` | %s | %s | `%s` | %s | %s | %ss | %s | %s |"
            % (
                finding["id"],
                finding["significance"],
                finding["status"],
                finding["source_task_id"],
                md_escape(finding["summary"]),
                md_escape(", ".join(finding["evidence"])),
                finding["age_seconds"],
                md_escape(finding["recommendation"] or "—"),
                md_escape(finding["disposition_rationale"] or "awaiting manager"),
            )
        )
    if not open_findings and not recent_findings:
        lines.append("| — | — | — | — | No findings recorded | — | — | — | — |")
    lines.extend(
        [
            "",
            "## Cases",
            "",
            "| ID | State | Source | External ID | Case | Open decisions |",
            "|---|---|---|---|---|---|",
        ]
    )
    active_cases = [
        case for case in snapshot["cases"] if case["status"] not in {"DONE", "CANCELLED"}
    ]
    recent_cases = sorted(
        [case for case in snapshot["cases"] if case["status"] in {"DONE", "CANCELLED"}],
        key=lambda item: item["updated_at"],
        reverse=True,
    )[:20]
    for case in active_cases + recent_cases:
        decisions = ", ".join("`%s`" % item["id"] for item in case["open_decisions"]) or "No"
        lines.append(
            "| `%s` | %s | %s | %s | %s | %s |"
            % (
                case["id"],
                completion_label(case),
                md_escape(case["source"]),
                md_escape(case["external_id"]),
                md_escape(case["title"]),
                decisions,
            )
        )
    if not active_cases and not recent_cases:
        lines.append("| — | — | — | — | No persistent-service cases | — |")
    lines.extend(
        [
            "",
            "## Workstreams",
            "",
            "| ID | State | Workstream | Intended outcome | Forecast | Needs human |",
            "|---|---|---|---|---|---|",
        ]
    )
    for workstream in snapshot["workstreams"]:
        needs_human = ", ".join("`%s`" % d["id"] for d in workstream["needs_human"]) or "No"
        lines.append(
            "| `%s` | %s | %s | %s | %s | %s |"
            % (
                workstream["id"],
                completion_label(workstream),
                md_escape(workstream["name"]),
                md_escape(workstream["outcome"]),
                md_escape(forecast_text(workstream)),
                needs_human,
            )
        )
    if not snapshot["workstreams"]:
        lines.append("| — | — | No workstreams defined | — | — | — |")
    lines.extend(
        [
            "",
            "## Policy workflows",
            "",
            "| Application | Policy | Version | State | Stages |",
            "|---|---|---|---|---|",
        ]
    )
    for application in snapshot["policy_applications"]:
        stage_summary = ", ".join(
            "%s:%s" % (task["stage_id"], task["status"]) for task in application["tasks"]
        )
        lines.append(
            "| `%s` | `%s` | %s | %s | %s |"
            % (
                application["id"],
                application["policy_id"],
                application["policy_version"],
                application["status"],
                md_escape(stage_summary),
            )
        )
    if not snapshot["policy_applications"]:
        lines.append("| — | No policy workflow applied | — | — | — |")
    lines.extend(
        [
            "",
            "## Delivery extensions",
            "",
            "| Extension | Version | Executor | Handles |",
            "|---|---|---|---|",
        ]
    )
    for extension in snapshot["extensions"]:
        lines.append(
            "| `%s` | %s | %s | %s |"
            % (
                extension["id"],
                extension["version"],
                extension["executor_type"],
                md_escape(", ".join(extension["handles"])),
            )
        )
    if not snapshot["extensions"]:
        lines.append("| — | — | No delivery extensions installed | — |")
    lines.extend(
        [
            "",
            "## Delivery outbox",
            "",
            "| ID | State | Channel | Extension | Subject | Attempts |",
            "|---|---|---|---|---|---|",
        ]
    )
    for delivery in snapshot["deliveries"][-20:]:
        lines.append(
            "| `%s` | %s | %s | `%s@%s` | %s | %s |"
            % (
                delivery["id"],
                delivery["status"],
                delivery["channel"],
                delivery["extension_id"],
                delivery["extension_version"],
                md_escape(delivery["subject"]),
                delivery["attempt_count"],
            )
        )
    if not snapshot["deliveries"]:
        lines.append("| — | — | — | No deliveries queued | — | — |")
    lines.extend(
        [
            "",
            "## Tasks",
            "",
            "| ID | Workstream | State | Kind | Owner | Title | Next action |",
            "|---|---|---|---|---|---|---|",
        ]
    )
    for task in snapshot["tasks"]:
        lines.append(
            "| `%s` | %s | %s | %s | %s | %s | %s |"
            % (
                task["id"],
                "`%s`" % task["workstream_id"] if task["workstream_id"] else "—",
                task["status"],
                task["kind"],
                md_escape(task["owner"] or "—"),
                md_escape(task["title"]),
                md_escape(task["next_action"] or "—"),
            )
        )
    if not snapshot["tasks"]:
        lines.append("| — | — | — | — | — | No tasks yet | — |")
    lines.extend(["", "## Open decisions", ""])
    open_decisions = [d for d in snapshot["decisions"] if d["status"] == "OPEN"]
    if not open_decisions:
        lines.append("No open decisions.")
    for decision in open_decisions:
        lines.extend(
            [
                "### `%s` — %s" % (decision["id"], decision["kind"]),
                "",
                decision["question"],
                "",
                "- Recommendation: %s" % (decision["recommendation"] or "None"),
                "- Blocks: %s" % ", ".join("`%s`" % x for x in decision["blocks"]),
                "",
            ]
        )
    lines.extend(["", "## Current facts", ""])
    current_facts = [fact for fact in snapshot["facts"] if fact["status"] == "CURRENT"]
    if not current_facts:
        lines.append("No current facts recorded.")
    for fact in current_facts:
        freshness = (
            "expires %s" % fact["expires_at"] if fact["expires_at"] else "no automatic expiry"
        )
        lines.append(
            "- **%s:** %s — observed %s from `%s`; %s"
            % (
                md_escape(fact["subject"]),
                md_escape(fact["value"]),
                fact["observed_at"],
                md_escape(fact["source"]),
                freshness,
            )
        )
    lines.extend(["", "## Recent events", ""])
    conn = connect(root)
    try:
        events = conn.execute("SELECT * FROM events ORDER BY seq DESC LIMIT 20").fetchall()
    finally:
        conn.close()
    for event in events:
        lines.append(
            "- `%s` %s — **%s** on `%s` by `%s`"
            % (
                event["id"],
                event["occurred_at"],
                event["event_type"],
                event["entity_id"],
                event["actor"],
            )
        )
    path = root / "views" / "BOARD.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path


def render_status_report(root):
    conn = connect(root)
    try:
        reconcile_conn(conn)
        snapshot = mission_snapshot(conn)
        health = doctor(conn)
        failed_runs = [
            dict(r)
            for r in conn.execute(
                "SELECT * FROM agent_runs WHERE exit_code IS NOT NULL AND exit_code <> 0 ORDER BY ended_at DESC LIMIT 5"
            )
        ]
    finally:
        conn.close()
    m = snapshot["mission"]
    open_decisions = [d for d in snapshot["decisions"] if d["status"] == "OPEN"]
    human = [
        d
        for d in open_decisions
        if d["kind"] in {"human_decision", "missing_access", "safety_stop"}
    ]
    other = [d for d in open_decisions if d not in human]
    active = [
        t
        for t in snapshot["tasks"]
        if t["status"] in ACTIVE_TASK_STATES or t["status"] == "BLOCKED"
    ]
    ready_tasks = [t for t in snapshot["tasks"] if t["status"] == "READY"]
    active_waits = [item for item in snapshot["external_waits"] if item["status"] == "WAITING"]
    open_findings = [item for item in snapshot["findings"] if item["status"] == "OPEN"]
    active_reviews = [
        item for item in snapshot["manager_reviews"] if item["status"] in {"PENDING", "RUNNING"}
    ]
    counts = {}
    for task in snapshot["tasks"]:
        counts[task["status"]] = counts.get(task["status"], 0) + 1
    open_cases = [case for case in snapshot["cases"] if case["status"] not in {"DONE", "CANCELLED"}]
    recent_terminal_cases = sorted(
        [case for case in snapshot["cases"] if case["status"] in {"DONE", "CANCELLED"}],
        key=lambda item: item["updated_at"],
        reverse=True,
    )[:10]
    lines = [
        "# Executive swarm status",
        "",
        "Generated %s" % utcnow(),
        "",
        "## Mission",
        "",
        "- Mode: **%s**" % m["mode"],
        "- Status: **%s**" % m["status"],
        "- Control: **%s**" % snapshot["runtime"]["desired_state"],
        "- Outcome: **%s**" % (snapshot["runtime"]["outcome"] or "Not yet completed"),
        "- Phase: **%s**" % m["phase"],
        "- Objective: %s" % m["objective"],
        "- Tasks: %s"
        % (
            ", ".join("%s %s" % (count, state) for state, count in sorted(counts.items())) or "none"
        ),
        "",
        "## Coordination",
        "",
    ]
    if not active_reviews:
        lines.append("No manager review is pending or running.")
    for review in active_reviews:
        reasons = "; ".join(item["reason"] for item in review["triggers"])
        lines.append(
            "- `%s` **%s/%s**; age %ss; triggers: %s"
            % (
                review["id"],
                review["status"],
                review["urgency"],
                review["age_seconds"],
                reasons,
            )
        )
    lines.extend(["", "## External waits", ""])
    if not active_waits:
        lines.append("No tasks are currently waiting on external conditions.")
    for wait in active_waits:
        resume = wait["next_check_at"] or "external signal"
        lines.append(
            "- `%s` task `%s` — %s; ref `%s`; resumes at %s or signal; deadline %s; waiting %ss"
            % (
                wait["id"],
                wait["task_id"],
                wait["condition"],
                wait["external_ref"],
                resume,
                wait["deadline_at"],
                wait["waiting_seconds"],
            )
        )
    lines.extend(["", "## Findings awaiting manager disposition", ""])
    if not open_findings:
        lines.append("No findings await manager disposition.")
    for finding in open_findings:
        lines.append(
            "- `%s` **%s** from task `%s` — %s; evidence: %s; age: %ss; impact: %s; recommendation: %s"
            % (
                finding["id"],
                finding["significance"],
                finding["source_task_id"],
                finding["summary"],
                ", ".join(finding["evidence"]),
                finding["age_seconds"],
                finding["mission_impact"],
                finding["recommendation"] or "none",
            )
        )
    lines.extend(["", "## Persistent-service cases", ""])
    if not open_cases and not recent_terminal_cases:
        lines.append("No cases have been submitted.")
    for case in open_cases + recent_terminal_cases:
        open_ids = ", ".join("`%s`" % item["id"] for item in case["open_decisions"]) or "none"
        lines.append(
            "- `%s` **%s** — %s; `%s:%s`; open decisions: %s"
            % (
                case["id"],
                completion_label(case),
                case["title"],
                case["source"],
                case["external_id"],
                open_ids,
            )
        )
    lines.extend(["", "## Major workstreams", ""])
    if not snapshot["workstreams"]:
        lines.append(
            "No workstreams have been defined yet. During early discovery this means the executive view is still forming."
        )
    for workstream in snapshot["workstreams"]:
        task_counts = (
            ", ".join(
                "%s %s" % (count, state)
                for state, count in sorted(workstream["task_counts"].items())
            )
            or "no linked tasks"
        )
        human_ids = ", ".join("`%s`" % d["id"] for d in workstream["needs_human"]) or "No"
        lines.extend(
            [
                "### %s (`%s`)" % (workstream["name"], workstream["id"]),
                "",
                "- Status: **%s**" % completion_label(workstream),
                "- Aiming to: %s" % workstream["outcome"],
                "- How it is going: %s"
                % (workstream["progress_summary"] or "No progress summary recorded yet"),
                "- Expected timing: %s" % forecast_text(workstream),
                "- Forecast basis: %s" % (workstream["forecast_basis"] or "None recorded"),
                "- Task state: %s" % task_counts,
                "- Needs anything from you: %s" % human_ids,
                "",
            ]
        )
    lines.extend(["", "## Policy workflows", ""])
    if not snapshot["policy_applications"]:
        lines.append("No policy workflows have been applied.")
    for application in snapshot["policy_applications"]:
        stage_summary = ", ".join(
            "%s=%s" % (task["stage_id"], task["status"]) for task in application["tasks"]
        )
        lines.append(
            "- `%s` `%s@%s` — **%s**; %s"
            % (
                application["id"],
                application["policy_id"],
                application["policy_version"],
                application["status"],
                stage_summary,
            )
        )
    lines.extend(["", "## Needs human input", ""])
    if not human:
        lines.append("Nothing currently needs human input.")
    for decision in human:
        lines.extend(
            [
                "### `%s`" % decision["id"],
                "",
                decision["question"],
                "",
                "- Recommendation: %s" % (decision["recommendation"] or "None recorded"),
                "- Options: %s" % ("; ".join(decision["options"]) or "No fixed options"),
                "- Blocks: %s" % ", ".join("`%s`" % x for x in decision["blocks"]),
                "",
            ]
        )
    lines.extend(["", "## Other urgent matters", ""])
    urgent_lines = []
    for problem in health["problems"]:
        urgent_lines.append(
            "- **%s:** `%s` — %s" % (problem["severity"], problem["entity"], problem["problem"])
        )
    for decision in other:
        urgent_lines.append(
            "- Open `%s` blocker `%s`: %s"
            % (decision["kind"], decision["id"], decision["question"])
        )
    for run in failed_runs:
        urgent_lines.append(
            "- Agent run `%s` exited %s at %s" % (run["id"], run["exit_code"], run["ended_at"])
        )
    for case in open_cases:
        if case["status"] == "WAITING_HUMAN":
            urgent_lines.append(
                "- Case `%s` is waiting for human input: %s"
                % (
                    case["id"],
                    ", ".join(item["id"] for item in case["open_decisions"]),
                )
            )
    for finding in open_findings:
        if finding["significance"] == "URGENT":
            urgent_lines.append(
                "- Urgent finding `%s` from task `%s`: %s"
                % (
                    finding["id"],
                    finding["source_task_id"],
                    finding["summary"],
                )
            )
    for wait in snapshot["external_waits"]:
        if wait["requires_attention"]:
            urgent_lines.append(
                "- External wait `%s` reached its deadline; task `%s` is ready for verification, not assumed successful."
                % (
                    wait["id"],
                    wait["task_id"],
                )
            )
    for delivery in snapshot["deliveries"]:
        if delivery["status"] == "UNKNOWN":
            urgent_lines.append(
                "- Delivery `%s` has an uncertain provider result. Inspect the provider, then use `delivery reconcile`; do not resend blindly."
                % delivery["id"]
            )
        elif delivery["status"] == "FAILED":
            urgent_lines.append(
                "- Delivery `%s` failed after %s attempt(s): %s"
                % (
                    delivery["id"],
                    delivery["attempt_count"],
                    delivery["last_error"] or "no error recorded",
                )
            )
        elif delivery["status"] == "PENDING" and delivery["attempt_count"]:
            urgent_lines.append(
                "- Delivery `%s` is pending again after %s attempt(s): %s"
                % (
                    delivery["id"],
                    delivery["attempt_count"],
                    delivery["last_error"] or "retry was explicitly authorized",
                )
            )
    lines.extend(urgent_lines or ["No urgent system matters detected."])
    lines.extend(["", "## Ready work", ""])
    if not ready_tasks:
        lines.append("No tasks are ready to run.")
    for task in ready_tasks:
        lines.append("- `%s` — %s" % (task["id"], task["title"]))
    lines.extend(["", "## Active work", ""])
    if not active:
        lines.append("No active or blocked work.")
    for task in active:
        workstream = (
            " in `%s`" % task["workstream_id"] if task["workstream_id"] else " (unassigned)"
        )
        lines.append(
            "- `%s` **%s**%s — %s; owner `%s`; last checkpoint %s"
            % (
                task["id"],
                task["status"],
                workstream,
                task["title"],
                task["owner"] or "none",
                task["last_checkpoint_at"] or "never",
            )
        )
    lines.extend(["", "## Next expected action", ""])
    if active_reviews:
        lines.append(
            "Run or finish the serialized manager review, then schedule from current state."
        )
    elif ready_tasks:
        lines.append("A bounded run can assign the ready work when capacity is available.")
    elif human:
        lines.append("The mission resumes after the listed human decision is recorded.")
    elif active_waits:
        checks = [wait["next_check_at"] for wait in active_waits if wait["next_check_at"]]
        next_check = min(checks) if checks else None
        if next_check:
            lines.append(
                "Resume at %s or sooner if a trusted external signal arrives." % next_check
            )
        else:
            lines.append(
                "Resume when a trusted external signal arrives; monitor the listed deadlines."
            )
    elif active:
        lines.append(
            "Wait for active work to checkpoint, finish, or raise a consequential finding."
        )
    elif m["mode"] == "SERVICE":
        lines.append("The service is idle until trusted ingress records a case or signal.")
    else:
        lines.append(
            "No next action is recorded; inspect mission completion conditions and current state."
        )
    path = root / "views" / "STATUS.md"
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return path
